services:
  postgres:
    image: postgres:16
    container_name: btc-analytics-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - btc_network

  rust-app:
    build:
      context: .
      dockerfile: Dockerfile.app
      target: runtime
    container_name: btc-analytics-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_HOST}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:${DATABASE_PORT}/${POSTGRES_DB}
      RUST_LOG: ${RUST_LOG:-btc_tx_stats=debug,info}
      RUST_BACKTRACE: '1'
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
    restart: unless-stopped
    network_mode: host

networks:
  btc_network:
    name: btc_network
    external: true

volumes:
  postgres_data:
